# Generated by Django 5.1.4 on 2025-02-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Predictiveapp', '0002_rename_message_notification_notmessage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='DoctorTable',
        ),
    ]
